# Generated by Django 3.0.1 on 2019-12-30 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20191230_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='product_photo',
            new_name='product',
        ),
    ]
